directories:
  output: dist-win-install
  buildResources: build
appId: com.scriptsmanager.app
productName: Scripts Manager
files:
  - filter:
      - main.js
      - preload.js
      - app/**/*
      - assets/**/*
      - node_modules/**/*
      - package.json
icon: assets/icon-256.png
win:
  icon: assets/icon-256.png
  target:
    - target: portable
      arch:
        - x64
    - target: nsis
      arch:
        - x64
portable:
  artifactName: ScriptsManager-${version}-portable.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  artifactName: ScriptsManager-${version}-setup.exe
  shortcutName: Scripts Manager
  uninstallDisplayName: Scripts Manager
linux:
  icon: assets/icon-256.png
  target:
    - target: AppImage
      arch:
        - x64
mac:
  icon: assets/icon-256.png
  target:
    - target: dmg
      arch:
        - x64
        - arm64
electronVersion: 27.3.11
